"""Synchronize generated version artifacts from ``pyproject.toml``."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from tomllib import load as toml_load

PYPROJECT_TOML = Path("pyproject.toml")
RUNTIME_VERSION_PY = Path("src/_version.py")
INNO_VERSION_ISS = Path("setup_version.iss")

_SUPPORTED_VERSION_RE = re.compile(r"^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(?:rc(?P<rc>\d+))?$")
_RELEASE_VERSION_RE = re.compile(r"^\d+\.\d+\.\d+(?:rc\d+)?$")


@dataclass(frozen=True)
class VersionArtifacts:
    display_version: str
    numeric_version: str


def validate_supported_version(version: str) -> str:
    """Validate and return a supported stable or rc version string."""
    if _SUPPORTED_VERSION_RE.fullmatch(version) is None:
        raise ValueError(f"Unsupported version {version!r}; use X.Y.Z or X.Y.ZrcN.")
    return version


def validate_release_version(version: str) -> str:
    """Validate the public release/tag form used by ``create_release.py``."""
    if _RELEASE_VERSION_RE.fullmatch(version) is None:
        raise ValueError(f"Unsupported release version {version!r}; use X.Y.Z or X.Y.ZrcN.")
    return version


def read_project_version(pyproject_path: Path = PYPROJECT_TOML) -> str:
    """Read the canonical project version from ``pyproject.toml``."""
    with pyproject_path.open("rb") as fh:
        data = toml_load(fh)

    try:
        version = data["project"]["version"]
    except KeyError as exc:
        raise ValueError(f"Missing [project].version in {pyproject_path}") from exc

    if not isinstance(version, str):
        raise ValueError(f"[project].version in {pyproject_path} must be a string.")
    return validate_supported_version(version)


def derive_version_artifacts(version: str) -> VersionArtifacts:
    """Derive generated display and Windows-numeric versions."""
    validated = validate_supported_version(version)
    match = _SUPPORTED_VERSION_RE.fullmatch(validated)
    assert match is not None  # guaranteed by validate_supported_version
    numeric_version = f"{match.group('major')}.{match.group('minor')}.{match.group('patch')}.0"
    display_version = f"{match.group('major')}.{match.group('minor')}.{match.group('patch')}"
    if match.group("rc") is not None:
        display_version = f"{display_version}rc{match.group('rc')}"
    return VersionArtifacts(display_version=display_version, numeric_version=numeric_version)


def render_runtime_version_module(artifacts: VersionArtifacts) -> str:
    """Render the generated Python runtime version module."""
    return (
        '"""Generated by sync_version.py from pyproject.toml. Do not edit manually."""\n\n'
        f'VERSION_STR = "{artifacts.display_version}"\n'
        f'VERSION_NUMERIC = "{artifacts.numeric_version}"\n'
    )


def render_inno_version_include(artifacts: VersionArtifacts) -> str:
    """Render the generated Inno Setup include file."""
    return (
        "; Generated by sync_version.py from pyproject.toml. Do not edit manually.\n"
        f'#define MyAppVersion "{artifacts.display_version}"\n'
        f'#define MyAppVersionNumeric "{artifacts.numeric_version}"\n'
    )


def expected_generated_files(
    *,
    pyproject_path: Path = PYPROJECT_TOML,
    runtime_version_path: Path = RUNTIME_VERSION_PY,
    inno_version_path: Path = INNO_VERSION_ISS,
) -> dict[Path, str]:
    """Return the expected generated files for the canonical project version."""
    artifacts = derive_version_artifacts(read_project_version(pyproject_path))
    return {
        runtime_version_path: render_runtime_version_module(artifacts),
        inno_version_path: render_inno_version_include(artifacts),
    }


def write_generated_files(
    *,
    pyproject_path: Path = PYPROJECT_TOML,
    runtime_version_path: Path = RUNTIME_VERSION_PY,
    inno_version_path: Path = INNO_VERSION_ISS,
) -> None:
    """Write generated version files if their contents differ."""
    for path, content in expected_generated_files(
        pyproject_path=pyproject_path,
        runtime_version_path=runtime_version_path,
        inno_version_path=inno_version_path,
    ).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")


def find_stale_generated_files(
    *,
    pyproject_path: Path = PYPROJECT_TOML,
    runtime_version_path: Path = RUNTIME_VERSION_PY,
    inno_version_path: Path = INNO_VERSION_ISS,
) -> list[Path]:
    """Return generated files that are missing or stale."""
    stale = []
    for path, expected in expected_generated_files(
        pyproject_path=pyproject_path,
        runtime_version_path=runtime_version_path,
        inno_version_path=inno_version_path,
    ).items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    return stale


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Synchronize generated version artifacts from pyproject.toml.")
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="Write generated version artifacts.")
    action.add_argument("--check", action="store_true", help="Fail if generated version artifacts are stale.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        if args.write:
            write_generated_files()
            return 0

        stale = find_stale_generated_files()
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 1

    if stale:
        print("Generated version artifacts are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run: uv run python sync_version.py --write", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised via CLI use, not unit tests
    raise SystemExit(main())
