name: Release on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release_on_tag:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_build.txt
      - name: Install Inno Setup (via Chocolatey)
        shell: pwsh
        run: |
          choco install innosetup --no-progress -y
      - name: Build installer
        shell: cmd
        env:
          AppId: ${{ secrets.INNO_APP_ID }}
        run: |
          call build.bat
      - name: Ensure SHA256 exists
        shell: pwsh
        run: |
          if (-not (Test-Path 'heat_sheet_pdf_highlighter_installer.exe.sha256')) {
            if (Test-Path 'heat_sheet_pdf_highlighter_installer.exe') {
              $h = (Get-FileHash 'heat_sheet_pdf_highlighter_installer.exe' -Algorithm SHA256).Hash.ToLower()
              "$h  heat_sheet_pdf_highlighter_installer.exe" | Out-File -Encoding ascii -NoNewline 'heat_sheet_pdf_highlighter_installer.exe.sha256'
            }
          }
      - name: Create GitHub Release from tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') }}
          files: |
            heat_sheet_pdf_highlighter_installer.exe
            heat_sheet_pdf_highlighter_installer.exe.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

